apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossip-sidecar
  labels:
    app: gossip-sidecar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gossip-sidecar
  template:
    metadata:
      labels:
        app: gossip-sidecar
    spec:
      containers:
      - name: gossip-sidecar
        image: registry.gitlab.com/kalexmills/k8s-gossip-sidecar:1.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - name: client-http
          containerPort: 80
        - name: peer
          containerPort: 46747
        env:
        - name: PEER_PORT
          value: "46747"
        - name: CLIENT_PORT
          value: "80"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: peer
          initialDelaySeconds: 15
          periodSeconds: 20
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: gossip-sidecar
  labels:
    app: gossip-sidecar
spec:
  clusterIP: None
  ports:
    - port: 46747
      name: gossip
  selector:
    app: gossip-sidecar
