apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossipcar
  labels:
    app: gossipcar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gossipcar
  template:
    metadata:
      labels:
        app: gossipcar
    spec:
      containers:
      - name: gossipcar
        image: registry.gitlab.com/kalexmills/k8s-gossipcar:v0.1.0
        imagePullPolicy: Always
        ports:
        - name: client-http
          containerPort: 80
        - name: peer
          containerPort: 46747
        env:
        - name: PEER_PORT
          value: "46747"
        - name: CLIENT_PORT
          value: "80"
        - name: SERVICE_DNS_NAME
          value: "gossipcar.default.svc.cluster.local"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: peer
          initialDelaySeconds: 15
          periodSeconds: 20
      imagePullSecrets:
        - name: gitlab-key
---
apiVersion: v1
kind: Service
metadata:
  name: gossipcar
  labels:
    app: gossipcar
spec:
  clusterIP: None
  ports:
    - port: 46747
      name: gossip
  selector:
    app: gossipcar
