apiVersion: apps/v1
kind: Service
metadata:
  name: gossipSidecar
  labels:
    app: gossipSidecar
spec:
  clusterIp: None
  ports:
    - port: 46747
      name: gossip
  selector:
    app: gossipSidecar
------------------------------------------------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossipSidecar
  labels:
    app: gossipSidecar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gossipSidecar
  template:
    metadata:
      labels:
        app: gossipSidecar
    spec:
      containers:
      - name: gossipSidecar
        image: k8s-gossip-sidecar:1.0.0
        imagePullPolicy: Always
        ports:
        - name: clientHttp
          containerPort: 80
        - name: peer
          containerPort: 46747
        envFrom:
        - configMapRef:
          name: gossipSidecar
------------------------------------------------------------------------------------------------------------------------
kind: ConfigMap
apiVersion: v1
metadata:
  name: gossipSidecar
  labels:
    name: gossipSidecar
data:
  PEER_PORT: 46747
  CLIENT_PORT: 80
  - name: MY_POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: MY_POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP